// src/constants/productCategories.js

export const PRODUCT_CATEGORIES = Object.freeze({
  ENTRANTES: 'ENTRANTES',
  GUNKAN: 'GUNKAN',
  ESPECIALES: 'ESPECIALES',
  NIGIRI: 'NIGIRI',
  TEMAKI: 'TEMAKI',
  ROLLS: 'ROLLS',
  FRITOS_AND_TACOS: 'FRITOS_AND_TACOS',
  VAPORES_AND_BAO: 'VAPORES_AND_BAO',
  ARROZ_AND_FIDEOS: 'ARROZ_AND_FIDEOS',
  POSTRES: 'POSTRES',
  BEBIDAS: 'BEBIDAS',
})

export const CATEGORY_LABELS = Object.freeze({
  [PRODUCT_CATEGORIES.ENTRANTES]: 'Entrantes',
  [PRODUCT_CATEGORIES.GUNKAN]: 'Gunkan',
  [PRODUCT_CATEGORIES.ESPECIALES]: 'Especiales',
  [PRODUCT_CATEGORIES.NIGIRI]: 'Nigiri',
  [PRODUCT_CATEGORIES.TEMAKI]: 'Temaki',
  [PRODUCT_CATEGORIES.ROLLS]: 'Rolls',
  [PRODUCT_CATEGORIES.FRITOS_AND_TACOS]: 'Fritos y Tacos',
  [PRODUCT_CATEGORIES.VAPORES_AND_BAO]: 'Vapores y Bao',
  [PRODUCT_CATEGORIES.ARROZ_AND_FIDEOS]: 'Arroz y Fideos',
  [PRODUCT_CATEGORIES.POSTRES]: 'Postres',
  [PRODUCT_CATEGORIES.BEBIDAS]: 'Bebidas',
})
